#服务端
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
#数据库端
Database:
  DBType: mysql
  Username: root
  Password: 123123
  Host: 127.0.0.1:3306
  DBName: douyin
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

